spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
server:
  port: 0

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"