spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

